# Generated by Django 5.2.4 on 2025-08-05 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_review_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
